### ISSUE TITLE
SDK Version Constraints

### ISSUE THREAD

**Issue by butlermatt** [pulyaevskiy/dart-kafka#2]
Just a quick note here. I see you have SDK Constraints set to 1.9 and up, however, You're also using null-aware operators in the source, which wasn't available until 1.12. You may wish to clamp down on the constraints as otherwise it'll cause some issues with anyone running anything from 1.9 - 1.11.x

**Comment by pulyaevskiy** [comment]
Thanks for your feedback! Good point, I just pushed update to `pubspec.yaml`.
