### ISSUE TITLE
API Error/Fetch Loop

### ISSUE THREAD

**Issue by butlermatt** [pulyaevskiy/dart-kafka#8]
When trying to subscribe to the remote server I mentioned in a another bug, after fixing the advertised hostname and port, I'm getting the follow loop.

```
[Kafka Logger]: Consumer: Running worker on host server1.mydomain.com:9092
[Kafka Logger]: Consumer: received API error 1 for topic testTopic:0
[Kafka Logger]: Offsets were reset. Forcing re-fetch.
[Kafka Logger]: Consumer: received API error 1 for topic testTopic:0
[Kafka Logger]: Offsets were reset. Forcing re-fetch.
[Kafka Logger]: Consumer: received API error 1 for topic testTopic:0
[Kafka Logger]: Offsets were reset. Forcing re-fetch.
[Kafka Logger]: Consumer: received API error 1 for topic testTopic:0
[Kafka Logger]: Offsets were reset. Forcing re-fetch.
[Kafka Logger]: Consumer: received API error 1 for topic testTopic:0
[Kafka Logger]: Offsets were reset. Forcing re-fetch.
[Kafka Logger]: Consumer: received API error 1 for topic testTopic:0
```

**Comment by pulyaevskiy** [comment]
I need to check this but it maybe because the topic is empty. The API error code 1 does not necessary mean there was an error, it just means that the requested offset does not exist. Which is the case when the topic is empty.

I'll take a look and get back to you.
Sorry for the delay here.

**Comment by butlermatt** [comment]
Just to follow up here, I believe that's what happening. More to the point, I believe the topic used to contain data, but that data has expired (eg more than the log retention time) leaving the topic empty.
